export * from "./About";
export * from "./Classes";
export * from "./ClassesDetail";
export * from "./Contact";
export * from "./Event";
export * from "./Faqs";
export * from "./Home";
export * from "./Intructor";
export * from "./Pricing";
